-- Cadastro completo do comprador (preenchido após a proposta ser aprovada).

CREATE TABLE `Comprador` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `propostaId` INTEGER NOT NULL,
  `leadId` INTEGER NULL,
  `nome` VARCHAR(191) NOT NULL,
  `sobrenome` VARCHAR(191) NULL,
  `cpf` VARCHAR(191) NOT NULL,
  `rg` VARCHAR(191) NULL,
  `orgaoExpedidor` VARCHAR(191) NULL,
  `dataNascimento` DATETIME(3) NULL,
  `nacionalidade` VARCHAR(191) NULL DEFAULT 'Brasileira',
  `estadoCivil` VARCHAR(191) NULL,
  `profissao` VARCHAR(191) NULL,
  `rendaMensal` DOUBLE NULL,
  `email` VARCHAR(191) NULL,
  `telefone` VARCHAR(191) NULL,
  `cep` VARCHAR(191) NULL,
  `logradouro` VARCHAR(191) NULL,
  `numero` VARCHAR(191) NULL,
  `complemento` VARCHAR(191) NULL,
  `bairro` VARCHAR(191) NULL,
  `cidade` VARCHAR(191) NULL,
  `estado` VARCHAR(191) NULL,
  `conjugeNome` VARCHAR(191) NULL,
  `conjugeCpf` VARCHAR(191) NULL,
  `conjugeRg` VARCHAR(191) NULL,
  `conjugeProfissao` VARCHAR(191) NULL,
  `conjugeRendaMensal` DOUBLE NULL,
  `observacoes` TEXT NULL,
  `concluido` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `Comprador_propostaId_key` (`propostaId`),
  INDEX `Comprador_leadId_idx` (`leadId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `Comprador_propostaId_fkey` FOREIGN KEY (`propostaId`) REFERENCES `Proposta` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Comprador_leadId_fkey` FOREIGN KEY (`leadId`) REFERENCES `Lead` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
